package com.example.springswagger.model;

import io.swagger.annotations.ApiModelProperty;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import javax.persistence.*;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import java.io.Serializable;
import java.util.List;

@Entity
@Table(name = "user")
@Getter
@Setter
@NoArgsConstructor

public class User  {

    @Id
    @GeneratedValue
    @ApiModelProperty(value = "Autogenerated id")
    @Column(name = "user_id")
    private Long id;
    @ApiModelProperty(value = "This is the user name")
    @NotNull
    @Size(min = 2, max = 30)
    @Column(name = "name")
    private String name;
    @ApiModelProperty(value = "This is the user code")
    @NotNull
    @Column(name = "user_code")
    private String userCode;
    @OneToOne(fetch = FetchType.LAZY, cascade = CascadeType.ALL)
    @JoinColumn(name = "user_details_id")
    private UserDetails userDetails;


    @ManyToMany(cascade = {CascadeType.PERSIST, CascadeType.MERGE, CascadeType.DETACH,
            CascadeType.REFRESH})
    @JoinTable(name = "user_diets"
            , joinColumns = {
            @JoinColumn(name = "user_id")
    }
            , inverseJoinColumns = {
            @JoinColumn(name = "diets_id")
    })
    private List<Diets> diets;

}
